### PR TITLE
Fixed devy role issue

### LINKED ISSUE #56: Bug: !devydeveloper only removing and not adding role

### PR DESCRIPTION
**Pull request by adavila0703**
There is something weird with how we are getting a "guild" and "roles" from a member. We can grab the guild_id and the member_roles from the incoming message. 

- Removed guildFromStateF and memberFromStateF
- Getting guild id and member rolls from message
- Confirmed that this fixed the previous bug with the devy bot.

Close #56

### CODE REVIEW

File: internal/devhubbot/commands.go [hunk 1]
```diff
@@ -195,25 +186,16 @@ func devyDeveloperCommandHandler(session *discordgo.Session, message *discordgo.
...
-		infra.Logger.Error().Err(err).Msg("member from state")
-
-		_, _ = channelMessageSendF(session, channel.ID, fmt.Sprintf("something went wrong toggle devy developer role for user %s", message.Author.Username))
-
-		return
-	}
-
 	currentlyHasRole := false
-	for _, roleID := range member.Roles {
+	for _, roleID := range message.Member.Roles {
```
Comment (DillonStreator) [inline internal/devhubbot/commands.go:190]: Yo nice find haha

Comment (DillonStreator) [reply internal/devhubbot/commands.go:190]: Can prob delete where this is defined and top of file, eh?

**Review by DillonStreator — APPROVED** [review]
LGTM
